---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart-user
  namespace: alpha01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-role
  namespace: alpha01
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    #    resourceNames: ["nginx", "nginx2"]
    verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
                                             # if you want to use `rollout status`
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-binding
  namespace: alpha01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart-role
subjects:
  - kind: ServiceAccount
    name: deployment-restart-user
    namespace: alpha01
